name: Dependency submission
run-name: Dependency submission - ${{ github.ref }}

on:
  workflow_dispatch:
  push:
  pull_request:

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - run: dotnet build ./ConsoleApp1
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.4
      - name: Dependency Review # Note that this step must be in the same job than the dependency submission - and after it
        uses: actions/dependency-review-action@v4
        if: github.event_name == 'pull_request'
        with:
          fail-on-severity: high
